### ISSUE TITLE
Alt Beacon Library does not deploy using latest Xamarin Studio 5.9.x

### ISSUE THREAD

**Issue by oldgitGB** [chrisriesgo/Android-AltBeacon-Library#6] opened 2015-06-23 08:59 UTC
Hi Chris

I'm trying to get the sample project from the Xamarin Alt Beacon project
(v.2.1.3 - https://components.xamarin.com/view/android-altbeacon-library)
to deploy but it fails every time with the exception outlined below.

I contacted Xamarin Support who can reproduce it and who advised me to raise it as an issue in this github repo.

Any help would be greatly appreciated!

Cheers,
Mike

**Xamarin response:**
I was able to reproduce the error you got using the sample for the Alt Beacon Component. And to be honest IO have no idea why that error is occurring. Ito seems the class is present. I suspect, though now where near 100% certain, that the issue may be on the library side due to changes with how we are generating Android Callable Wrappers. See: http://developer.xamarin.com/releases/android/xamarin.android_5/xamarin.android_5.1/#Android_Callable_Wrapper_Naming

If this is the case, this will likely have to remedied by the Component's developer. Third party components are supported by the Component author. I see they have the library in a github, so perhaps filing an issue there would be the best way to move forward.
https://github.com/chrisriesgo/Android-AltBeacon-Library

**The Exception:**
[AndroidRuntime] FATAL EXCEPTION: main
[AndroidRuntime] Process: androidaltbeaconlibrary.sample, PID: 4422
[AndroidRuntime] java.lang.RuntimeException: Unable to instantiate
application androidaltbeaconlibrary.sample.BeaconReferenceApplication:
java.lang.ClassNotFoundException: Didn't find class
"androidaltbeaconlibrary.sample.BeaconReferenceApplication" on path:
DexPathList[[zip file "/data/app/androidaltbeaconlibrary.
sample-1/base.apk"],nativeLibraryDirectories=[/data/app/
androidaltbeaconlibrary.sample-1/lib/arm64, /vendor/lib64, /system/lib64]]
[AndroidRuntime] at android.app.LoadedApk.makeApplication(LoadedApk.
java:649)
[AndroidRuntime] at android.app.ActivityThread.handleBindApplication(
ActivityThread.java:5225)
[AndroidRuntime] at android.app.ActivityThread.access$1600(ActivityThread.
java:182)
[AndroidRuntime] at android.app.ActivityThread$H.
handleMessage(ActivityThread.java:1536)
[AndroidRuntime] at android.os.Handler.dispatchMessage(Handler.java:102)
[AndroidRuntime] at android.os.Looper.loop(Looper.java:145)
[AndroidRuntime] at android.app.ActivityThread.
main(ActivityThread.java:6141)
[AndroidRuntime] at java.lang.reflect.Method.invoke(Native Method)
[AndroidRuntime] at java.lang.reflect.Method.invoke(Method.java:372)
[AndroidRuntime] at com.android.internal.os.ZygoteInit$
MethodAndArgsCaller.run(ZygoteInit.java:1399)
[AndroidRuntime] at com.android.internal.os.ZygoteInit.main(ZygoteInit.
java:1194)
[AndroidRuntime] Caused by: java.lang.ClassNotFoundException: Didn't find
class "androidaltbeaconlibrary.sample.BeaconReferenceApplication" on path:
DexPathList[[zip file "/data/app/androidaltbeaconlibrary.
sample-1/base.apk"],nativeLibraryDirectories=[/data/app/
androidaltbeaconlibrary.sample-1/lib/arm64, /vendor/lib64, /system/lib64]]
[AndroidRuntime] at dalvik.system.BaseDexClassLoader.findClass(
BaseDexClassLoader.java:56)
[AndroidRuntime] at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
[AndroidRuntime] at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
[AndroidRuntime] at android.app.Instrumentation.newApplication(
Instrumentation.java:988)
[AndroidRuntime] at android.app.LoadedApk.makeApplication(LoadedApk.
java:644)
[AndroidRuntime] ... 10 more
[AndroidRuntime] Suppressed: java.lang.ClassNotFoundException:
androidaltbeaconlibrary.sample.BeaconReferenceApplication
[AndroidRuntime] at java.lang.Class.classForName(Native Method)
[AndroidRuntime] at java.lang.BootClassLoader.findClass(ClassLoader.java:
781)
[AndroidRuntime] at java.lang.BootClassLoader.loadClass(ClassLoader.java:
841)
[AndroidRuntime] at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
[AndroidRuntime] ... 13 more
[AndroidRuntime] Caused by: java.lang.NoClassDefFoundError: Class not
found using the boot class loader; no stack available

**Comment by bholmes** [comment] 2015-06-24 02:58
I have a suggestion for those using the Component in the store.  As mentioned above the issue is with Android Callable Wrappers.  The entries in the AndroidManifest file are not matching the actual class names.  As suggested you can use attributes to generate the info for the AndroidManifest.  Somewhere in your application simply extend the classes within the bindings and add attributes.  Also remove all the corresponding elements in the manifest file.

``` csharp
[Service (Enabled=true, Exported = false, IsolatedProcess=false, Label="Beacon")]
public class MyBeaconService : BeaconService
{

}

[Service (Enabled=true, Exported = false, Label="Beacon")]
public class MyBeaconIntentProcessor : BeaconIntentProcessor
{

}

[BroadcastReceiver, IntentFilter (new [] {"android.intent.action.BOOT_COMPLETED", "android.intent.action.ACTION_POWER_CONNECTED", "android.intent.action.ACTION_POWER_DISCONNECTED"})]
public class MyStartupBroadcastReceiver : AltBeaconOrg.BoundBeacon.Startup.StartupBroadcastReceiver
{

}
```

There is one last issue to resolve with this sample.  The Application name is not being found as it is listed in the AndroidManifest.  Add the missing attribute and remove the xml attributes of the application element.

``` csharp
[Application (Label = "AltBeacon Sample", Icon = "@drawable/altbeacon")]
public class BeaconReferenceApplication : Application, IBootstrapNotifier
```

Your cleaned up AndroidManifest file should look like this.

``` xml
<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android" android:versionCode="1" android:versionName="1.0" package="androidaltbeaconlibrary.sample">
	<uses-sdk android:minSdkVersion="18" />

	<uses-permission android:name="android.permission.BLUETOOTH" />
	<uses-permission android:name="android.permission.BLUETOOTH_ADMIN" />
	<uses-permission android:name="android.permission.RECEIVE_BOOT_COMPLETED" />

	<application>

	</application>
</manifest>
```

**Comment by chrisriesgo** [comment] 2015-06-24 03:41
@oldgitGB @bholmes Thanks for bringing this to my attention, guys. I'll try to get this remedied by the end of the week.

**Comment by oldgitGB** [comment] 2015-06-24 10:09
Thanks Chris ... great library btw!

[image: Corethree Ltd] <http://corethree.net>

Michael Smith / Chief Development Officer
michael.smith@corethree.net <joy.roxas@corethree.net>
m: +44 (0)7971 025454

Corethree Ltd
t: +44 (0)845 557 0475
corethree.net <http://www.corethree.net>

[image: Facebook] <https://www.facebook.com/CorethreeHQ> [image: Twitter]
<https://twitter.com/corethree> [image: Linkedin]
<https://www.linkedin.com/company/corethree>

**Comment by rusty21** [comment] 2015-06-25 20:38
Is anyone else having problems with the backgrounding? I downloaded this sample, applied the suggested application fixes. Everything builds and runs, and i shows that I've entered/exited beacons when the app is running. If I close the application by going to the application switcher and swiping to close the app, nothing happens when I enter the range of an iBeacon. I modified the code slightly to pop up a notification when you enter the range of any beacon but the notification never shows.

**Comment by chrisriesgo** [comment] 2015-06-27 12:53
@rusty21 - The "backgrounding" logic is trickier than you might expect. Please take a look at this past Issue thread where someone had a similar issue. I briefly listed out the scenarios that you should expect background monitoring of beacons:  https://github.com/chrisriesgo/Android-AltBeacon-Library/issues/2#issuecomment-74858279

**Comment by chrisriesgo** [comment] 2015-06-27 12:58
@oldgitGB - I was able to confirm the issue that you're having. By making the changes that @bholmes suggested, the app was able to launch. I'm going to do some further testing to ensure that Ranging and Monitoring of beacons will works as expected. 

Once everything checks out, I'll dispatch new nuget packages and Xamarin components.

**Comment by chrisriesgo** [comment] 2015-06-27 13:26
So far, normal ranging and monitoring seems to be working, and if the app is backgrounded and a new beacon comes available, a notification is displayed in the status bar. I'm going to move forward with packaging the demo updates.

**Comment by chrisriesgo** [comment] 2015-06-27 15:43
New component has been submitted. I'll close this issue once it has been accepted.

**Closed** 2015-08-05 02:43 UTC
Labels: bug
